import { StyleSheet } from "react-native";

// ==========================================
// WARNA — TEMA ELEGAN & MINIMAL
// Background utama: Deep Soft Blue
// Card: putih/off-white
// ==========================================
export const COLORS = {
  // Primary — Deep Soft Blue (background & aksi utama)
  primary: "#5B8FA8",
  primaryDark: "#4A7A91",
  primaryDarker: "#3A6478",
  primaryLight: "#7FAEC4",
  primarySoft: "#E4EFF4",
  primarySoftBorder: "#C4DCE6",

  // Secondary — Soft Warm Yellow
  accent: "#E7C96B",
  accentDark: "#B8932E",
  accentLight: "#F0DCA0",
  accentSoft: "#FBF4DC",
  accentSoftBorder: "#EDDDA8",
  accentText: "#6B5320",

  // Tertiary — Soft Mint
  success: "#8BC7A5",
  successDark: "#4E8F6B",
  successLight: "#A8D4BB",
  successSoft: "#E6F4EC",
  successSoftBorder: "#C4E4D2",

  // Netral
  bg: "#5B8FA8",
  bgAlt: "#F1F5F7",
  card: "#FFFFFF",
  border: "#DCE4E9",
  borderLight: "#EDF1F4",
  borderStrong: "#C8D3DA",

  // Teks
  textDark: "#1F2A33",
  textMid: "#5A6B77",
  textLight: "#8B98A4",
  textInverse: "#FFFFFF",
  textOnBlue: "#FFFFFF",
  textOnBlueSoft: "rgba(255,255,255,0.85)",

  // Status
  danger: "#C25E5E",
  dangerDark: "#A04444",
  dangerSoft: "#FBEDED",
  dangerSoftBorder: "#F0CFCF",

  warn: "#C99A3E",
  warnSoft: "#FBF3DF",
  warnSoftBorder: "#EBD9AE",

  // Overlay
  overlayDark: "rgba(31,42,51,0.45)",
  overlayBlue: "rgba(91,143,168,0.10)",
  overlayBlueSoft: "rgba(91,143,168,0.16)",
  overlayYellow: "rgba(231,201,107,0.14)",
  overlayYellowSoft: "rgba(231,201,107,0.22)",
  overlayMint: "rgba(139,199,165,0.14)",
  overlayMintSoft: "rgba(139,199,165,0.22)",
  overlayWhite08: "rgba(255,255,255,0.08)",
  overlayWhite12: "rgba(255,255,255,0.12)",
  overlayWhite20: "rgba(255,255,255,0.20)",
  overlayWhite30: "rgba(255,255,255,0.30)",

  // Progress
  progressTrackBg: "#E1E8ED",
  progressTrackBorder: "#CDD8DF",
};

// ==========================================
// PRESET SHADOW
// ==========================================
const shadowSoft = {
  elevation: 1,
  shadowColor: "#1F2A33",
  shadowOpacity: 0.05,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 2 },
};

const shadowMedium = {
  elevation: 2,
  shadowColor: "#1F2A33",
  shadowOpacity: 0.08,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 4 },
};

const shadowStrong = {
  elevation: 3,
  shadowColor: "#1F2A33",
  shadowOpacity: 0.15,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 5 },
};

const shadowYellow = {
  elevation: 2,
  shadowColor: COLORS.accentDark,
  shadowOpacity: 0.18,
  shadowRadius: 8,
  shadowOffset: { width: 0, height: 3 },
};

const shadowDialog = {
  elevation: 12,
  shadowColor: "#000000",
  shadowOpacity: 0.22,
  shadowRadius: 30,
  shadowOffset: { width: 0, height: 14 },
};

// ==========================================
// TYPOGRAPHY — Nunito
// ==========================================
export const FONTS = {
  regular: "Nunito_400Regular",
  medium: "Nunito_500Medium",
  semiBold: "Nunito_600SemiBold",
  bold: "Nunito_700Bold",
  extraBold: "Nunito_800ExtraBold",
};

// ==========================================
// STYLE UTAMA
// ==========================================
export const styles = StyleSheet.create({
  // LAYOUT
  container: { flex: 1, backgroundColor: COLORS.primary },
  keyboardContainer: { flex: 1, backgroundColor: COLORS.primary },
  scrollContent: { flexGrow: 1 },
  content: { padding: 20, paddingBottom: 40 },
  tabContent: { flex: 1 },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.primary,
    padding: 24,
    overflow: "hidden",
  },
  rowCenter: { flexDirection: "row", alignItems: "center" },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  // SPLASH
  splashContainer: {
    flex: 1,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  splashLogoBox: {
    width: 72,
    height: 72,
    borderRadius: 22,
    backgroundColor: COLORS.card,
    alignItems: "center",
    justifyContent: "center",
    ...shadowSoft,
  },
  splashTitle: {
    marginTop: 14,
    fontSize: 22,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textInverse,
    letterSpacing: 0.2,
  },

  // LOADING
  loadingScreen: {
    flex: 1,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingRingOuter: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingRingInner: {
    width: 130,
    height: 130,
    borderRadius: 65,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowStrong,
  },
  loadingOrbitDot: {
    position: "absolute",
    top: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.accent,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  loadingLogoBox: {
    width: 84,
    height: 84,
    borderRadius: 26,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    ...shadowStrong,
  },
  loadingTitle: {
    marginTop: 32,
    fontSize: 22,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textInverse,
    letterSpacing: 0.4,
  },
  loadingSubtitle: {
    marginTop: 6,
    fontSize: 12.5,
    fontFamily: FONTS.medium,
    color: "rgba(255,255,255,0.85)",
    letterSpacing: 0.2,
  },
  loadingDotsRow: {
    marginTop: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  loadingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.6)",
  },

  // LOADING — LOGO FOCUS
  loadingLogoWrap: {
    width: 140,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingLogoOuterRing: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.25)",
  },
  loadingLogoInnerRing: {
    position: "absolute",
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  loadingLogoBoxMain: {
    width: 88,
    height: 88,
    borderRadius: 26,
    backgroundColor: COLORS.card,
    alignItems: "center",
    justifyContent: "center",
    ...shadowStrong,
  },

  decorCircle1: { width: 0, height: 0 },
  decorCircle2: { width: 0, height: 0 },

  // HEADER
  header: {
    paddingTop: 56,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: COLORS.card,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    marginTop: 2,
    color: COLORS.textMid,
    fontSize: 12.5,
    fontFamily: FONTS.medium,
  },
  logoutButton: {
    backgroundColor: COLORS.bgAlt,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  logoutText: {
    color: COLORS.textDark,
    fontWeight: "700",
    fontFamily: FONTS.bold,
    fontSize: 12,
  },

  // ==========================================
  // HEADER DENGAN LOGO
  // ==========================================
  headerWithLogo: {
    paddingTop: 56,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: COLORS.card,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerLogoBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    ...shadowSoft,
  },
  headerLogoBoxSmall: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    ...shadowSoft,
  },
  headerTextWrap: {
    flex: 1,
  },
  headerTitleWithLogo: {
    fontSize: 18,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    letterSpacing: 0.2,
  },
  headerSubtitleWithLogo: {
    marginTop: 1,
    color: COLORS.textMid,
    fontSize: 12,
    fontFamily: FONTS.medium,
  },
  headerPageTitle: {
    fontSize: 20,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    letterSpacing: 0.2,
  },
  headerPageSubtitle: {
    marginTop: 1,
    color: COLORS.textMid,
    fontSize: 12,
    fontFamily: FONTS.medium,
  },

  // CARD
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: COLORS.card,
    padding: 28,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowMedium,
  },
  cardSmall: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  cardMedium: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },

  // LOGO
  logoWrap: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  logoBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    ...shadowSoft,
  },

  // TEKS UMUM
  title: {
    fontSize: 26,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    textAlign: "center",
    color: COLORS.textDark,
    letterSpacing: 0.2,
  },
  titleAccent: { width: 0, height: 0 },
  subtitle: {
    textAlign: "center",
    color: COLORS.textMid,
    marginTop: 14,
    marginBottom: 24,
    lineHeight: 20,
    fontSize: 13,
    fontFamily: FONTS.regular,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textInverse,
    letterSpacing: 0.2,
  },
  pageTitleAccent: { width: 0, height: 0 },
  pageSubtitle: {
    color: "rgba(255,255,255,0.85)",
    marginTop: 4,
    marginBottom: 20,
    fontSize: 13,
    fontFamily: FONTS.regular,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    color: COLORS.textDark,
    marginBottom: 12,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    fontFamily: FONTS.semiBold,
    color: COLORS.textDark,
    marginBottom: 8,
    letterSpacing: 0.1,
  },
  labelForm: {
    fontSize: 13,
    fontWeight: "700",
    fontFamily: FONTS.semiBold,
    color: COLORS.textDark,
    marginBottom: 8,
    marginTop: 4,
    letterSpacing: 0.1,
  },
  hint: {
    fontSize: 11,
    color: COLORS.textMid,
    fontFamily: FONTS.regular,
    marginBottom: 14,
    paddingLeft: 2,
  },
  textDark: { color: COLORS.textDark, fontFamily: FONTS.regular },
  textMid: { color: COLORS.textMid, fontFamily: FONTS.regular },
  textLight: { color: COLORS.textLight, fontFamily: FONTS.regular },

  // TAB
  tabRow: {
    flexDirection: "row",
    backgroundColor: COLORS.bgAlt,
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 9,
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.22,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  tabText: {
    fontSize: 13.5,
    fontWeight: "700",
    fontFamily: FONTS.bold,
    color: COLORS.textMid,
  },
  tabTextActive: { color: COLORS.textInverse },

  // INPUT
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    marginBottom: 18,
    paddingHorizontal: 14,
  },
  inputIcon: { marginRight: 10 },
  inputField: {
    flex: 1,
    height: 52,
    color: COLORS.textDark,
    fontSize: 14.5,
    fontFamily: FONTS.medium,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 14,
    color: COLORS.textDark,
    backgroundColor: COLORS.card,
    marginBottom: 14,
    fontSize: 14,
    fontFamily: FONTS.medium,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 14,
  },
  eyeButton: {
    paddingHorizontal: 6,
    paddingVertical: 8,
    justifyContent: "center",
    alignItems: "center",
  },

  // DATE
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: COLORS.card,
    marginBottom: 8,
    gap: 12,
  },
  dateIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  dateButtonText: {
    flex: 1,
    color: COLORS.textDark,
    fontSize: 13.5,
    fontWeight: "600",
    fontFamily: FONTS.semiBold,
  },

  // JAM & MENIT
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  timeInputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 56,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    backgroundColor: COLORS.card,
    paddingHorizontal: 12,
    gap: 6,
  },
  timeInput: {
    flex: 1,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    textAlign: "center",
    padding: 0,
    height: "100%",
  },
  timeUnit: {
    fontSize: 11,
    color: COLORS.textMid,
    fontFamily: FONTS.bold,
    fontWeight: "700",
  },
  timeSeparator: {
    fontSize: 22,
    fontWeight: "900",
    fontFamily: FONTS.extraBold,
    color: COLORS.textLight,
    marginBottom: 4,
  },

  // DURASI
  durationWrap: {
    flexDirection: "row",
    alignItems: "center",
    height: 56,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 12,
    backgroundColor: COLORS.card,
    paddingHorizontal: 14,
    gap: 10,
    marginBottom: 8,
  },
  durationInput: {
    flex: 1,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    padding: 0,
    height: "100%",
  },
  durationUnit: {
    fontSize: 12.5,
    color: COLORS.textMid,
    fontFamily: FONTS.bold,
    fontWeight: "700",
  },
  durationPreview: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 6,
    marginBottom: 14,
    alignSelf: "flex-start",
  },
  durationPreviewText: {
    color: COLORS.textMid,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: FONTS.bold,
  },

  // PRESET
  presetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  presetChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: COLORS.bgAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  presetChipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primaryDark,
  },
  presetChipText: {
    fontSize: 11.5,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    color: COLORS.textMid,
  },
  presetChipTextActive: { color: COLORS.textInverse },

  // BUTTON
  button: {
    height: 54,
    backgroundColor: COLORS.primary,
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    ...shadowSoft,
  },
  buttonDisabled: { opacity: 0.6 },
  buttonText: {
    color: COLORS.textInverse,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    letterSpacing: 0.3,
  },
  primaryButton: {
    height: 52,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    ...shadowSoft,
  },
  primaryButtonText: {
    color: COLORS.textInverse,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    fontSize: 14,
    letterSpacing: 0.2,
  },
  switchLink: { marginTop: 20, alignItems: "center" },
  switchText: {
    color: COLORS.textMid,
    fontSize: 13,
    fontFamily: FONTS.regular,
  },
  switchTextBold: {
    color: COLORS.primaryDarker,
    fontWeight: "800",
    fontFamily: FONTS.bold,
  },

  // BOTTOM NAV
  bottomNav: {
    height: 68,
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    ...shadowSoft,
  },
  navItem: { alignItems: "center", justifyContent: "center", flex: 1 },
  navText: {
    fontSize: 10.5,
    color: COLORS.textLight,
    marginTop: 3,
    fontWeight: "700",
    fontFamily: FONTS.bold,
  },
  navActive: { color: COLORS.primaryDarker },

  // WELCOME CARD
  welcomeCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    overflow: "hidden",
    position: "relative",
    ...shadowMedium,
  },
  welcomeCircle1: {
    position: "absolute",
    top: -60,
    right: -60,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: COLORS.primary,
    opacity: 0.06,
  },
  welcomeCircle2: {
    position: "absolute",
    bottom: -70,
    left: -50,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: COLORS.accent,
    opacity: 0.1,
  },
  welcomeAccentLine: { width: 0, height: 0 },
  welcomeContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    zIndex: 1,
  },
  welcomeLeft: { flex: 1, paddingRight: 10 },
  welcomeRight: { alignItems: "flex-end" },
  welcomeGreeting: {
    color: COLORS.textMid,
    fontSize: 12.5,
    fontWeight: "700",
    fontFamily: FONTS.semiBold,
    letterSpacing: 0.2,
  },
  welcomeName: {
    color: COLORS.textDark,
    fontSize: 21,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    marginTop: 2,
    letterSpacing: 0.2,
  },
  username: {
    color: COLORS.textDark,
    fontSize: 21,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    marginTop: 2,
    letterSpacing: 0.2,
  },
  welcomeDivider: { width: 0, height: 0 },
  welcomeSubtitle: {
    color: COLORS.textMid,
    fontSize: 11.5,
    fontFamily: FONTS.medium,
    marginTop: 0,
  },

  // GREETING SUBTITLE DENGAN ICON
  welcomeSubtitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  welcomeSubtitleIcon: {
    width: 22,
    height: 22,
    borderRadius: 7,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.primarySoftBorder,
  },

  // PREMIUM BADGE
  premiumBadge: {
    backgroundColor: COLORS.bgAlt,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  premiumBadgeActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accentDark,
  },
  premiumBadgeText: {
    color: COLORS.textDark,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10,
    letterSpacing: 0.5,
  },
  premiumBadgeTextActive: { color: "#5A4518" },

  // FREE BADGE
  freeBadge: {
    backgroundColor: COLORS.bgAlt,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1.5,
    borderColor: "#1F2A33",
    ...shadowSoft,
  },
  freeBadgeText: {
    color: "#000000",
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10,
    letterSpacing: 0.5,
  },
  freeBadgeIconWrap: {
    width: 16,
    height: 16,
    borderRadius: 5,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },

  // Title chips
  welcomeTitlesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  welcomeTitleChip: {
    backgroundColor: COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COLORS.primarySoftBorder,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  welcomeTitleChipText: {
    fontSize: 11,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    color: COLORS.primaryDarker,
    letterSpacing: 0.2,
  },

  // CUSTOM WARNA USERNAME
  welcomeNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  welcomeNameFlex: {
    flexShrink: 1,
  },
  welcomeColorBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COLORS.primarySoftBorder,
    alignItems: "center",
    justifyContent: "center",
  },

  // COLOR PICKER MODAL
  colorPickerBackdrop: {
    flex: 1,
    backgroundColor: COLORS.overlayDark,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  colorPickerCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowDialog,
  },
  colorPickerTitle: {
    fontSize: 16.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    textAlign: "center",
    letterSpacing: 0.1,
  },
  colorPickerSubtitle: {
    fontSize: 12.5,
    fontFamily: FONTS.regular,
    color: COLORS.textMid,
    textAlign: "center",
    marginTop: 4,
    marginBottom: 18,
  },
  colorPickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
  },
  colorPickerSwatch: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: COLORS.borderStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  colorPickerSwatchActive: {
    borderColor: COLORS.primaryDarker,
    borderWidth: 3,
  },

  // STATS
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 16 },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  statCardOrnament: { width: 0, height: 0 },
  statIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  statNumber: {
    fontSize: 19,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    marginTop: 10,
  },
  statLabel: {
    color: COLORS.textMid,
    fontSize: 11,
    marginTop: 2,
    fontWeight: "700",
    fontFamily: FONTS.semiBold,
    letterSpacing: 0.1,
  },

  // PROGRESS CARD
  progressCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
    position: "relative",
    ...shadowSoft,
  },
  progressOrnamentTopRight: { width: 0, height: 0 },
  progressOrnamentBottomLeft: { width: 0, height: 0 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  progressPercent: {
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.primaryDarker,
    fontSize: 16,
  },
  progressBackground: {
    height: 8,
    backgroundColor: COLORS.progressTrackBg,
    borderRadius: 20,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 20,
  },
  progressDescription: {
    marginTop: 10,
    color: COLORS.textMid,
    fontSize: 11.5,
    fontFamily: FONTS.medium,
  },
  progress: {
    marginTop: 10,
    color: COLORS.textMid,
    fontSize: 11.5,
    fontFamily: FONTS.medium,
  },
  progressBackgroundLarge: {
    width: "100%",
    height: 10,
    backgroundColor: COLORS.progressTrackBg,
    borderRadius: 20,
    overflow: "hidden",
  },

  // FORM
  formCard: {
    backgroundColor: COLORS.card,
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  formAccentBar: { width: 0, height: 0 },
  formHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 18,
    marginTop: 4,
  },
  formIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  formHeaderText: { flex: 1 },
  formTitle: {
    fontSize: 15.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    letterSpacing: 0.1,
  },
  formSubtitle: {
    fontSize: 11,
    color: COLORS.textMid,
    marginTop: 2,
    fontFamily: FONTS.medium,
  },

  // LIST HEADER
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  listHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  listHeaderIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  listTitle: {
    fontSize: 16,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textInverse,
    letterSpacing: 0.1,
  },
  listHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  listCountBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  listCountText: {
    color: COLORS.textInverse,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 11,
  },

  // SCHEDULE CARD
  scheduleCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  scheduleCornerAccent: { width: 0, height: 0 },
  scheduleCornerAccentActive: { width: 0, height: 0 },
  scheduleCompleted: {
    backgroundColor: COLORS.successSoft,
    borderColor: COLORS.successSoftBorder,
  },
  scheduleStudying: {
    borderColor: COLORS.primary,
    borderWidth: 1.5,
    backgroundColor: COLORS.primarySoft,
  },
  scheduleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 10,
  },
  subject: {
    flex: 1,
    fontSize: 15.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  scheduleText: {
    color: COLORS.textMid,
    marginTop: 3,
    fontSize: 13,
    fontFamily: FONTS.regular,
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.bgAlt,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    gap: 5,
  },
  infoText: {
    fontSize: 11.5,
    color: COLORS.textDark,
    fontFamily: FONTS.semiBold,
    fontWeight: "700",
  },

  // COUNTDOWN
  countdownBox: {
    backgroundColor: COLORS.bgAlt,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 12,
    alignSelf: "stretch",
  },
  countdownBlock: { flexDirection: "column", gap: 2 },
  countdownInner: { flexDirection: "row", alignItems: "center", gap: 6 },
  countdownText: {
    color: "#B8932E",
    fontSize: 11.5,
    fontFamily: FONTS.bold,
    fontWeight: "800",
  },
  countdownTextStrong: {
    color: "#B8932E",
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 12,
  },

  // TIMER
  timerBox: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 12,
    alignSelf: "flex-start",
    overflow: "hidden",
    position: "relative",
    ...shadowSoft,
  },
  timer: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  timerOrnament: { width: 0, height: 0 },
  timerLabel: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 9,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    marginBottom: 3,
    letterSpacing: 1.2,
  },
  timerValue: {
    color: COLORS.textInverse,
    fontSize: 22,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    letterSpacing: 1.5,
  },

  divider: { height: 1, backgroundColor: COLORS.border, marginBottom: 12 },

  // ACTION BUTTONS
  actionsRow: { flexDirection: "row", gap: 8 },
  actionBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
  },
  actionBtnText: { fontSize: 11.5, fontFamily: FONTS.bold, fontWeight: "800" },
  actionBtnReminder: {
    backgroundColor: COLORS.bgAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  actionBtnTextReminder: { color: COLORS.textDark },
  actionBtnComplete: {
    backgroundColor: COLORS.primary,
    ...shadowSoft,
  },
  actionBtnTextComplete: { color: COLORS.textInverse },
  actionBtnDone: {
    backgroundColor: COLORS.successSoft,
    borderWidth: 1,
    borderColor: COLORS.successSoftBorder,
  },
  actionBtnTextDone: { color: COLORS.successDark },
  actionBtnFailed: {
    backgroundColor: COLORS.dangerSoft,
    borderWidth: 1,
    borderColor: COLORS.dangerSoftBorder,
  },
  actionBtnTextFailed: { color: COLORS.dangerDark },
  actionBtnDelete: {
    backgroundColor: COLORS.bgAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  actionBtnTextDelete: { color: COLORS.textMid },
  actionBtnDisabled: { opacity: 0.5 },

  // STATUS BADGE
  statusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  statusWaiting: { backgroundColor: COLORS.bgAlt },
  statusWaitingText: {
    color: COLORS.textMid,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10.5,
  },
  statusStudying: { backgroundColor: COLORS.primarySoft },
  statusStudyingText: {
    color: COLORS.primaryDarker,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10.5,
  },
  statusFinished: { backgroundColor: COLORS.successSoft },
  statusFinishedText: {
    color: COLORS.successDark,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10.5,
  },
  statusFailed: { backgroundColor: COLORS.dangerSoft },
  statusFailedText: {
    color: COLORS.dangerDark,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10.5,
  },

  // EMPTY
  emptyCard: {
    backgroundColor: COLORS.card,
    padding: 30,
    borderRadius: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: "dashed",
  },
  emptyOrnament1: { width: 0, height: 0 },
  emptyOrnament2: { width: 0, height: 0 },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyIcon: { fontSize: 40 },
  emptyTitle: {
    fontSize: 15.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    marginTop: 14,
    color: COLORS.textDark,
  },
  emptyText: {
    color: COLORS.textMid,
    marginTop: 6,
    textAlign: "center",
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: FONTS.regular,
    paddingHorizontal: 20,
  },

  // PROGRESS PAGE
  bigProgressCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 26,
    alignItems: "center",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
    position: "relative",
    ...shadowSoft,
  },
  bigProgressOrnament1: {
    position: "absolute",
    top: -60,
    right: -60,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: COLORS.primary,
    opacity: 0.06,
  },
  bigProgressOrnament2: {
    position: "absolute",
    bottom: -70,
    left: -50,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: COLORS.accent,
    opacity: 0.1,
  },
  bigProgressNumber: {
    fontSize: 46,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.primaryDarker,
    letterSpacing: 0.5,
    zIndex: 1,
  },
  bigProgressLabel: {
    color: COLORS.textMid,
    marginBottom: 20,
    fontSize: 12.5,
    fontFamily: FONTS.semiBold,
    zIndex: 1,
  },
  statsLargeRow: { flexDirection: "row", gap: 12, marginBottom: 15 },
  statsLargeCard: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  statsLargeOrnament: { width: 0, height: 0 },
  statIconWrapLarge: {
    width: 44,
    height: 44,
    borderRadius: 13,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  largeNumber: {
    fontSize: 23,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
  },
  largeLabel: {
    color: COLORS.textMid,
    textAlign: "center",
    fontSize: 11.5,
    fontFamily: FONTS.semiBold,
  },

  // LOCK / PREMIUM
  lockCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  lockOrnament: { width: 0, height: 0 },
  lockIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  lockTitle: {
    fontSize: 17,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    marginTop: 14,
  },
  lockText: {
    color: COLORS.textMid,
    textAlign: "center",
    lineHeight: 19,
    marginTop: 8,
    marginBottom: 18,
    fontSize: 12.5,
    fontFamily: FONTS.regular,
  },
  premiumCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  premiumButton: {
    backgroundColor: COLORS.accent,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    ...shadowYellow,
  },
  premiumButtonText: {
    color: COLORS.accentText,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    fontSize: 13.5,
  },

  // ANALYSIS
  analysisCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  analysisOrnament: { width: 0, height: 0 },
  analysisText: {
    color: COLORS.textMid,
    lineHeight: 19,
    marginBottom: 20,
    fontSize: 12.5,
    fontFamily: FONTS.regular,
  },
  chartArea: {
    height: 180,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingHorizontal: 10,
  },
  chartColumn: {
    alignItems: "center",
    justifyContent: "flex-end",
    height: "100%",
  },
  chartBar: {
    width: 24,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    minHeight: 10,
  },
  chartLabel: {
    fontSize: 9,
    color: COLORS.textMid,
    marginTop: 6,
    fontFamily: FONTS.medium,
  },
  chartDescription: {
    color: COLORS.textLight,
    fontSize: 11,
    marginTop: 12,
    textAlign: "center",
    fontFamily: FONTS.regular,
  },

  // ANALISIS BELAJAR — LOCK
  analysisLockCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
    marginBottom: 16,
  },
  analysisLockIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: COLORS.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.accentSoftBorder,
  },
  analysisLockTitle: {
    fontSize: 17,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    marginTop: 14,
  },
  analysisLockText: {
    color: COLORS.textMid,
    textAlign: "center",
    lineHeight: 19,
    marginTop: 8,
    marginBottom: 18,
    fontSize: 12.5,
    fontFamily: FONTS.regular,
  },

  // PREMIUM HERO
  premiumHero: {
    backgroundColor: COLORS.primaryDarker,
    borderRadius: 20,
    padding: 26,
    alignItems: "center",
    marginBottom: 22,
    overflow: "hidden",
    position: "relative",
    ...shadowStrong,
  },
  premiumHeroCircle1: {
    position: "absolute",
    top: -60,
    right: -60,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: COLORS.textInverse,
    opacity: 0.05,
  },
  premiumHeroCircle2: {
    position: "absolute",
    bottom: -70,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: COLORS.accent,
    opacity: 0.1,
  },
  premiumHeroCircle3: {
    position: "absolute",
    top: "40%",
    left: -40,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: COLORS.primary,
    opacity: 0.2,
  },
  premiumCrownWrap: {
    width: 68,
    height: 68,
    borderRadius: 22,
    backgroundColor: "rgba(231,201,107,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  crown: { fontSize: 48 },
  premiumTitle: {
    color: COLORS.textInverse,
    fontSize: 21,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    marginTop: 14,
    letterSpacing: 0.2,
  },
  premiumSubtitle: {
    color: "rgba(255,255,255,0.85)",
    textAlign: "center",
    marginTop: 7,
    lineHeight: 18,
    fontSize: 12.5,
    fontFamily: FONTS.regular,
  },
  premiumBuyButton: {
    backgroundColor: COLORS.accent,
    marginTop: 20,
    paddingHorizontal: 22,
    paddingVertical: 13,
    borderRadius: 11,
    ...shadowYellow,
  },
  premiumBuyText: {
    color: COLORS.accentText,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    fontSize: 13.5,
  },
  activePremium: {
    backgroundColor: COLORS.success,
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  activePremiumText: {
    color: COLORS.textInverse,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    fontSize: 12,
    letterSpacing: 0.6,
  },

  // SECTION HEADER PREMIUM
  premiumSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
    marginBottom: 14,
  },
  premiumSectionIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: COLORS.primaryDarker,
    alignItems: "center",
    justifyContent: "center",
    ...shadowSoft,
  },
  premiumSectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textInverse,
    letterSpacing: 0.1,
  },
  premiumSectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  premiumSectionBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  premiumSectionBadgeText: {
    color: COLORS.textInverse,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    fontSize: 10.5,
  },

  // FEATURE
  featureCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 11,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  featureOrnament: { width: 0, height: 0 },
  featureIconBox: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  featureIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  featureInfo: { flex: 1 },
  featureTitle: {
    fontSize: 14.5,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    color: COLORS.textDark,
  },
  featureDescription: {
    color: COLORS.textMid,
    marginTop: 3,
    lineHeight: 17,
    fontSize: 11.5,
    fontFamily: FONTS.regular,
  },

  // PRODUCT
  productCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 20,
    marginBottom: 13,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  productOrnament: { width: 0, height: 0 },
  productIconBox: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: COLORS.accentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  productTitle: {
    fontSize: 15.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    marginTop: 10,
  },
  productDescription: {
    color: COLORS.textMid,
    lineHeight: 18,
    marginTop: 5,
    fontSize: 12.5,
    fontFamily: FONTS.regular,
  },
  productPrice: {
    fontSize: 16.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.primaryDarker,
    marginTop: 12,
  },
  productButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 11,
    alignItems: "center",
    marginTop: 12,
  },
  productButtonText: {
    color: COLORS.textInverse,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    fontSize: 13,
    letterSpacing: 0.2,
  },

  // IAP
  productHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  iapStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  iapStatusBadgeLocked: {
    backgroundColor: COLORS.bgAlt,
    borderColor: COLORS.border,
  },
  iapStatusBadgeUnlocked: {
    backgroundColor: COLORS.successSoft,
    borderColor: COLORS.successSoftBorder,
  },
  iapStatusBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    letterSpacing: 0.4,
  },
  iapStatusBadgeTextLocked: { color: COLORS.textMid },
  iapStatusBadgeTextUnlocked: { color: COLORS.successDark },

  iapContentList: {
    marginTop: 12,
    gap: 8,
  },
  iapContentItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.bgAlt,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  iapContentIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  iapContentTextWrap: {
    flex: 1,
  },
  iapContentTitle: {
    fontSize: 13,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    color: COLORS.textDark,
    letterSpacing: 0.1,
  },
  iapContentDesc: {
    fontSize: 10.5,
    fontFamily: FONTS.regular,
    color: COLORS.textMid,
    marginTop: 2,
  },

  // ACHIEVEMENT
  achSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
    marginBottom: 14,
  },
  achSectionIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  achSectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textInverse,
    letterSpacing: 0.1,
  },
  achSectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.25)",
  },

  achMainCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
  },
  achCatHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  achCatHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  achCatIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  achCatTitle: {
    fontSize: 14.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    letterSpacing: 0.1,
  },
  achCatTotal: {
    fontSize: 12.5,
    fontWeight: "700",
    fontFamily: FONTS.semiBold,
    color: COLORS.textMid,
    marginTop: 1,
  },
  achDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginTop: 14,
    marginBottom: 14,
  },

  achItem: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    backgroundColor: COLORS.bgAlt,
  },
  achItemReady: {
    borderColor: COLORS.accentDark,
    backgroundColor: COLORS.accentSoft,
  },
  achItemClaimed: {
    borderColor: COLORS.successSoftBorder,
    backgroundColor: COLORS.successSoft,
  },
  achItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 10,
  },
  achItemTitleWrap: { flex: 1 },
  achItemTitle: {
    fontSize: 14,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    letterSpacing: 0.1,
  },
  achItemDesc: {
    fontSize: 11.5,
    fontFamily: FONTS.regular,
    color: COLORS.textMid,
    marginTop: 2,
  },
  achItemBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
  },
  achItemBadgeLocked: {
    backgroundColor: COLORS.bgAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  achItemBadgeReady: {
    backgroundColor: COLORS.accent,
    borderWidth: 1,
    borderColor: COLORS.accentDark,
  },
  achItemBadgeClaimed: {
    backgroundColor: COLORS.success,
    borderWidth: 1,
    borderColor: COLORS.successDark,
  },
  achItemBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    fontFamily: FONTS.bold,
    letterSpacing: 0.4,
  },
  achItemBadgeTextLocked: { color: COLORS.textMid },
  achItemBadgeTextReady: { color: "#5A4518" },
  achItemBadgeTextClaimed: { color: COLORS.textInverse },

  achProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  achProgressText: {
    fontSize: 11,
    fontFamily: FONTS.semiBold,
    fontWeight: "700",
    color: COLORS.textMid,
  },
  achProgressTextReady: {
    color: COLORS.accentText,
  },
  achProgressTextClaimed: {
    color: COLORS.successDark,
  },
  achProgressTrack: {
    height: 6,
    backgroundColor: COLORS.progressTrackBg,
    borderRadius: 20,
    overflow: "hidden",
    marginBottom: 10,
  },
  achProgressFill: {
    height: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 20,
  },
  achProgressFillReady: {
    backgroundColor: COLORS.accentDark,
  },
  achProgressFillClaimed: {
    backgroundColor: COLORS.success,
  },

  achItemActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 2,
  },
  achClaimBtn: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    ...shadowSoft,
  },
  achClaimBtnText: {
    color: COLORS.textInverse,
    fontSize: 12.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    letterSpacing: 0.2,
  },
  achInstallBtn: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    backgroundColor: COLORS.bgAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  achInstallBtnActive: {
    backgroundColor: COLORS.primarySoft,
    borderColor: COLORS.primary,
  },
  achInstallBtnText: {
    color: COLORS.textDark,
    fontSize: 12.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    letterSpacing: 0.2,
  },
  achInstallBtnTextActive: {
    color: COLORS.primaryDarker,
  },

  achLockCard: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadowSoft,
    marginBottom: 16,
  },
  achLockIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: COLORS.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.accentSoftBorder,
  },
  achLockTitle: {
    fontSize: 17,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    marginTop: 14,
  },
  achLockText: {
    color: COLORS.textMid,
    textAlign: "center",
    lineHeight: 19,
    marginTop: 8,
    marginBottom: 18,
    fontSize: 12.5,
    fontFamily: FONTS.regular,
  },

  // ICON CONTAINER
  iconContainer: { alignItems: "center", justifyContent: "center" },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 13,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBoxSmall: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBoxLarge: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },

  // MODAL
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlayDark,
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: 15.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
  },
  modalCancel: {
    color: COLORS.textMid,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: FONTS.semiBold,
  },
  modalDone: {
    color: COLORS.primaryDarker,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
  },

  // ==========================================
  // VIDEO MODAL (IAP)
  // ==========================================
  videoModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.88)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  videoModalCard: {
    width: "100%",
    maxWidth: 720,
    backgroundColor: "#000000",
    borderRadius: 16,
    overflow: "hidden",
    ...shadowDialog,
  },
  videoModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  videoModalTitle: {
    flex: 1,
    color: COLORS.textInverse,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    letterSpacing: 0.2,
  },
  videoModalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  videoModalPlayerWrap: {
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: "#000000",
  },
  videoModalPlayer: {
    width: "100%",
    height: "100%",
  },
  videoModalLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  videoModalLoadingText: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 12.5,
    fontFamily: FONTS.medium,
    marginTop: 6,
  },

  // ALERT
  alertBackdrop: {
    flex: 1,
    backgroundColor: COLORS.overlayDark,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  alertCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: COLORS.card,
    borderRadius: 18,
    paddingTop: 24,
    paddingBottom: 18,
    paddingHorizontal: 22,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
    position: "relative",
    ...shadowDialog,
  },
  alertAccentLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  alertAccentBlue: { backgroundColor: COLORS.primary },
  alertAccentYellow: { backgroundColor: COLORS.accent },
  alertAccentMint: { backgroundColor: COLORS.success },
  alertAccentNeutral: { backgroundColor: COLORS.borderStrong },
  alertIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    borderWidth: 1,
    marginBottom: 14,
  },
  alertIconBlue: {
    backgroundColor: COLORS.primarySoft,
    borderColor: COLORS.primarySoftBorder,
  },
  alertIconYellow: {
    backgroundColor: COLORS.accentSoft,
    borderColor: COLORS.accentSoftBorder,
  },
  alertIconMint: {
    backgroundColor: COLORS.successSoft,
    borderColor: COLORS.successSoftBorder,
  },
  alertIconNeutral: {
    backgroundColor: COLORS.bgAlt,
    borderColor: COLORS.borderStrong,
  },
  alertTitle: {
    fontSize: 16.5,
    fontWeight: "800",
    fontFamily: FONTS.extraBold,
    color: COLORS.textDark,
    textAlign: "center",
    letterSpacing: 0.1,
  },
  alertMessage: {
    fontSize: 13.5,
    fontFamily: FONTS.regular,
    color: COLORS.textMid,
    textAlign: "center",
    lineHeight: 20,
    marginTop: 8,
  },
  alertActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 22,
  },
  alertActionsColumn: {
    flexDirection: "column",
    gap: 8,
    marginTop: 22,
  },
  alertBtnBase: {
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    flexDirection: "row",
    gap: 6,
  },
  alertBtnPrimary: {
    backgroundColor: COLORS.primary,
    ...shadowSoft,
  },
  alertBtnPrimaryText: {
    color: COLORS.textInverse,
    fontFamily: FONTS.extraBold,
    fontWeight: "800",
    fontSize: 14,
    letterSpacing: 0.2,
  },
  alertBtnSecondary: {
    backgroundColor: COLORS.bgAlt,
    borderWidth: 1.5,
    borderColor: COLORS.borderStrong,
  },
  alertBtnSecondaryText: {
    color: COLORS.textDark,
    fontFamily: FONTS.bold,
    fontWeight: "700",
    fontSize: 14,
  },
  alertBtnDestructive: {
    backgroundColor: COLORS.danger,
    ...shadowSoft,
  },
  alertBtnDestructiveText: {
    color: COLORS.textInverse,
    fontFamily: FONTS.extraBold,
    fontWeight: "800",
    fontSize: 14,
  },
  alertBtnFull: { width: "100%" },
});

export default styles;
